IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LMS.BookIssued')
BEGIN
    drop table dbo.[LMS.BookIssued]
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LMS.BookDescription')
BEGIN
    drop table dbo.[LMS.BookDescription]
END
GO

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LMS.BookDetails')
BEGIN
    drop table dbo.[LMS.BookDetails]
END
GO



IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LMS.Address')
BEGIN
    drop table dbo.[LMS.Address]
END
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LMS.UserDetails')
BEGIN
    drop table dbo.[LMS.UserDetails]
END
GO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SchemaVersions' )
BEGIN
    DROP TABLE SchemaVersions
END
GO

IF EXISTS(SELECT 1 FROM sys.schemas WHERE name = 'LMS' )
BEGIN
    DROP SCHEMA LMS
END
GO